### ISSUE TITLE
 UNEXPECTED ERROR ON LOGIN, please try again and verify your connection!

### ISSUE THREAD

**Issue by Abdulsamipy** [alpdias/instagram-bot#1]
Hi, so i have been trying to login and been getting the follow error even i have installed the gecko driver and added the path to my environment variable 

`DRIVER ERROR! Check installed drive or path.
UNEXPECTED ERROR ON LOGIN, please try again and verify your connection!
`

**Comment by alpdias** [comment]
Remove the retries and exceptions (try / except) and try running again and it will show you the specific error. Then return me with the error that I can help you. You can try to increase the time between runs too (sleep), depending on your connection it may give error before you can log in.

**Comment by Abdulsamipy** [comment]
> Remove the retries and exceptions (try / except) and try running again and it will show you the specific error. Then return me with the error that I can help you. You can try to increase the time between runs too (sleep), depending on your connection it may give error before you can log in.

pardon me can you kindly tell me how to run it?

**Comment by usaegetta** [comment]
hi there, regarding stories where do I have to add number of stories?
all works ok but tasks ends immediately no story is been opened.
Many thanks

**Comment by alpdias** [comment]
Of course, do you understand a little bit of Python or programming?
