### ISSUE TITLE
Mais de um comentário ....

### ISSUE THREAD

**Issue by thalesortega** [alpdias/instagram-bot#10]
Primeiramente, parabens pelo codigo

Gostaria de saber se é possível colocar comentarios randomicos.. tipo.. separar eles por algum caracter e ele fazer o input de forma randomica.. 

Obrigado

Thales

**Comment by alpdias** [comment]
Boa noite Thales, obrigado! E sim é possível fazer isso, mas no momento meu código não realiza essa função, talvez em uma próxima atualização eu adicione isso.
