### ISSUE TITLE
Não passa para o próximo perfil

### ISSUE THREAD

**Issue by acymiranda** [alpdias/instagram-bot#12]
Olá! 

Tentei usando o gecko e chromedriver, mas eles até abrem um perfil e curte, mas nunca passa pro próximo... precisa configurar algo a mais?

Abs!

**Comment by acymiranda** [comment]
Olá, está funcionando, sim! Obrigado!

**Comment by alpdias** [comment]
@acymiranda fico feliz que tenha consigo, valeu!

**Comment by diego1989ms** [comment]
![IMG_20210323_231736176](https://user-images.githubusercontent.com/80019468/112378094-47718500-8cc5-11eb-9b71-281a2209588b.jpg)
Aqui uma foto do erro amigo

**Comment by alpdias** [comment]
@diego1989ms você lembrou de descompactar os arquivos do _geckodriver_? Por que o caminho já é automático se não tiver mudado a organização das pastas do projeto
