### ISSUE TITLE
Not posting comments with botdraw.py

### ISSUE THREAD

**Issue by iammobina** [alpdias/instagram-bot#15]
Hello, I recently used your code to post a comment on one of my favorite posts. Everything works fine except when the comment is written in the text field and it must then be posted.
your code can not post comments :(

**Comment by iammobina** [comment]
I guess you should update your code...

**Comment by alpdias** [comment]
Hi @iammobina hope all is well out there! It's been a long time since I've updated my codes, but everyone has explanations and details of how they work, I hope you can tweak a little and make it work if you wish, thanks for the feedback!
