### ISSUE TITLE
Plugin pyfiglet

### ISSUE THREAD

**Issue by felipecremm** [alpdias/instagram-bot#16]
Boa Tarde,
Estou com um problema que não está reconhecendo o plugin
from pyfiglet import Figlet

e já realizei a instalação.
![image](https://user-images.githubusercontent.com/59665630/166984003-fc341be8-448f-4269-ac05-a2acb5a8cde5.png)

Você teria como me ajudar ?

obrigado por enquanto.

**Comment by alpdias** [comment]
Olá, desculpa a demora a responder, no momento não estou mais atualizando meus repositórios, mas caso queria muito rodar esse script você pode simplesmente remover esse modulo e todas as linhas que o mencionam, ele é usado somente para criar uma 'imagem' de capa, como um nome para o script.
