### ISSUE TITLE
stories from followers

### ISSUE THREAD

**Issue by usaegetta** [alpdias/instagram-bot#2]
hi there, is there a way to watch storyes from unfollowed people?

**Comment by alpdias** [comment]
Yes it is possible, but I would have to find a page that makes the stories available at random, as it happens in the application, on the web page we don't have this option, at least I don't know.

**Comment by usaegetta** [comment]
I have done half work could I send you an email?

**Comment by alpdias** [comment]
Sorry I don't share email, create a fork of the code, implement what you did inside and send me the repository, then we can work together

**Comment by usaegetta** [comment]
ok
