### ISSUE TITLE
Como saber se o botão "Curtir" já foi clicado?

### ISSUE THREAD

**Issue by danilogazzoli** [alpdias/instagram-bot#3]
Olá, os bots são bem bacanas mas eles curtem independente do botão "Curtir" estar marcado ou não.

**Comment by alpdias** [comment]
Olá @danilogazzoli, obrigado pelo feedback. E sim eles curtem independente de já ter curtido antes, o que acaba gerando a ação de 'descurtir' a foto, logo mais irei trabalhar essa parte e arrumar.
