### ISSUE TITLE
command execution error

### ISSUE THREAD

**Issue by victorcas123** [alpdias/instagram-bot#4]
I tried to run the command on my windows 10 cmd and it says: '' '$' is not recognized as an internal command
or external, an operable program or a batch file. ''
Provides the right command for windows please

**Comment by alpdias** [comment]
The character '$' only serves to represent a division between the phrase and the code, sorry if I confused you, just run **python bot-instagram.py**

**Comment by victorcas123** [comment]
no problems bro, but still i'm not getting it, i already installed java, geckodriver and modules, but when i execute the command in cmd it says '' python: can't open file 'bot-instagram.py': [ Errno 2] No such file or directory ''
can you help me?

**Comment by victorcas123** [comment]
no problems bro, but still i'm not getting it, i already installed java, geckodriver and modules, but when i execute the command in cmd it says '' python: can't open file 'bot-instagram.py': [ Errno 2] No such file or directory ''
can you help me?

**Comment by alpdias** [comment]
Yes, can you send me a screenshot of the screen where the error occurs?

**Comment by victorcas123** [comment]
![erro 1](https://user-images.githubusercontent.com/69027077/89052419-0db1cf80-d32c-11ea-9375-90c2360afc42.png)

**Comment by alpdias** [comment]
The problem is occurring because he is not finding the file in the folder, you have to open the terminal inside the folder where the file is, or before bot-instagram.py put the file path.  Example: python C: /home/user/bot-instagram-python/bot-instagram.py

**Comment by victorcas123** [comment]
right, but the file that is to put is the one you made available for download that is written '' bot-instagram-python-master '' right?

**Comment by victorcas123** [comment]
bro, now this is happening,  sorry to be bothering you, is that I really am not good with these things and I really need to be able to activate the comment bot
![erro 2](https://user-images.githubusercontent.com/69027077/89054922-f674e100-d32f-11ea-8905-8f52ccf9ed7f.png)
![erro 3](https://user-images.githubusercontent.com/69027077/89054931-f7a60e00-d32f-11ea-8839-641eb23030f9.png)

**Comment by alpdias** [comment]
Try to follow these steps:

> place the program folder in your Downloads folder 

> Open the terminal type: cd C:\Users\your_user_here\Downloads\bot-instagram-python-master\src\

> Type: **python bot-instagram.py**


Basically you have to open the terminal inside the folder that contains the **bot-instagram.py** file and call it with the **python bot-instagram.py** command

**Comment by victorcas123** [comment]
thank you

**Comment by victorcas123** [comment]
bro, other error 
![erro500](https://user-images.githubusercontent.com/69027077/89061240-c121c080-d33a-11ea-8c2e-ae89599bae86.png)

**Comment by alpdias** [comment]
What was placed in the 'way' entrance?

**Comment by victorcas123** [comment]
![erro 501](https://user-images.githubusercontent.com/69027077/89061715-8f5d2980-d33b-11ea-9fe8-35ba704596f0.png)
only the underline part

**Comment by alpdias** [comment]
In the 'way' entry you must enter the path to the geckodriver program. Inside the folder you downloaded open the windows folder and unzip the file **geckodriver-v0.26.0-win64.zip**, then go back to the program and at the entry 'way' put the path to the folder you unzipped, it should look something like this:

C:\Users\your_user_here\Downloads\bot-instagram-python-master\geckodriver\windows\geckodriver-v0.26.0-win64

**Comment by victorcas123** [comment]
still giving the same error, and brother, if the way is the geckodriver, how will I choose the publication I want you to comment on?
![erro 510](https://user-images.githubusercontent.com/69027077/89062689-4a39f700-d33d-11ea-9ec7-5aa7d1b0cfd0.png)
![erro 511](https://user-images.githubusercontent.com/69027077/89062857-8ec59280-d33d-11ea-8f32-406a4f62ae3b.png)

**Comment by alpdias** [comment]
The publication is chosen by the 'hastag'. Still showing error?

**Comment by victorcas123** [comment]
brother, I got almost everything, but at the last minute of this error,what should I put in the rashtag?
![erro 150](https://user-images.githubusercontent.com/69027077/89064203-f2e95600-d33f-11ea-8fe3-bbebb807ef95.png)

**Comment by victorcas123** [comment]
coincidentally I had already put the url of the publication in the hashtag, however this error in photo 150

**Comment by alpdias** [comment]
The 'hashtag' is the tag of the photo where the # is used, just put the name of the hashtag, such as: **likeforlike**

**Comment by victorcas123** [comment]
but when the publication has no hashtag? 
![erro 705](https://user-images.githubusercontent.com/69027077/89064981-4f994080-d341-11ea-91bf-9d9727196c99.png)

**Comment by alpdias** [comment]
The bot does not have this function, it just searches for hashtag, which is the easiest way to search for grouping images. Were you able to make it work?

**Comment by victorcas123** [comment]
I did it, but it was in a random post that had the same hashtag and only commented 1 time

**Comment by victorcas123** [comment]
can you put up how many hashtags?

**Comment by alpdias** [comment]
Just one hashtag at a time, as to comment several times on a photo, is a good idea, even though I hadn't thought about it, and it should be very useful to use in sweepstakes. I can add this function later.

**Comment by victorcas123** [comment]
make this improvement please bro, because it falls into any random publication, you cannot select the publication

**Comment by alpdias** [comment]
Hello friend, a new function was added to make several comments on pictures of the draw !!
