### ISSUE TITLE
getting driver error

### ISSUE THREAD

**Issue by jatin-pahuja** [alpdias/instagram-bot#6]
hello mate
i did everything and i am getting this error
![bot](https://user-images.githubusercontent.com/56190028/90748530-ed07e480-e2ef-11ea-943a-c5cc22badebc.JPG)

**Comment by alpdias** [comment]
Hello, sorry for the delay in the answer, can you show the path you put at the entrance 'way'? It would usually be something like: C:\Users\youruser\Documents\geckodriver\windows (it is not necessary to point the program, only the raw path)

**Comment by jatin-pahuja** [comment]
yes the path is this only as you can see
![bot](https://user-images.githubusercontent.com/56190028/91152397-882c0000-e6dc-11ea-8c1f-6aa467727a6f.JPG)

**Comment by alpdias** [comment]
Has the program (geckodriver) been unzipped too?

**Comment by jatin-pahuja** [comment]
i had unzipped it

**Comment by alpdias** [comment]
If all these steps have been followed I don't know what may be causing this error, what you can do to check together if you have a notion of Python, is to remove the 'try' and 'except' from the execution and let the error show in the terminal for have a more specific view, soon I will be updating the script and creating a more complete check for this error

**Comment by jatin-pahuja** [comment]
okay friend i will try

**Comment by alpdias** [comment]
Hello @jatin-pahuja, the error has been corrected, download the code again and try to run again. Now for the program to work correctly you just need to enter the 'geckodriver' folder, choose the folder for your system and unzip the program, without changing any path.

**Comment by jatin-pahuja** [comment]
Brother it still is the same error but now its not asking for way in configuration its just asking for delay and then login info no way information

**Comment by alpdias** [comment]
Okay, enter one of the scripts and remove the 'try' and 'except' from the executions, this will show the error more clearly and then show the error here so I can help you

![image](https://user-images.githubusercontent.com/52184239/94996424-005ad080-057b-11eb-8f32-b4ce00ca2f48.png)

**Comment by kona104** [comment]
your bot is awesome, easy to use! After I change the following code it works great.
 # load browser drive in to var and open
    try:
        driver = webdriver.Firefox()

but I have another request, sometimes it had a "try again later"pop up box, I need to click confirm. Can you write some script to do it from your bot?

**Comment by alpdias** [comment]
Thanks for the comment! I'm glad you managed to use it. Put here a print of this part so that I can see it more easily and try to help you, soon I will add new functions to the bot and I can include this too.
