### ISSUE TITLE
dificuldades com o caminho do geckodriver

### ISSUE THREAD

**Issue by csanzinho** [alpdias/instagram-bot#7]
C:\Users\carlos\python.exe C:/Users/carlos/Desktop/bot-instagram-python-master/bot-instagram-python-master/src/bot-instagram.py
Traceback (most recent call last):
  File "C:/Users/carlos/Desktop/bot-instagram-python-master/bot-instagram-python-master/src/bot-instagram.py", line 12, in <module>
    import botLike
  File "C:\Users\carlos\Desktop\bot-instagram-python-master\bot-instagram-python-master\src\botLike.py", line 57
    driver = webdriver.Firefox(executable_path=f'{C:\Users\carlos\Desktop\bot-instagram-python-master\bot-instagram-python-master\geckodriver\windows}') # geckodriver path https://github.com/mozilla/geckodriver/releases/tag/v0.26.0
                                               ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 0-1: truncated \UXXXXXXXX escape

Process finished with exit code 1

**Comment by alpdias** [comment]
Hello @csanzinho , I apologize for the error, this error of path and some others are already being solved for easier use and will be updated until tomorrow.

**Comment by alpdias** [comment]
Hello @csanzinho, the error has been corrected, download the code again and try to run again. Now for the program to work correctly you just need to enter the 'geckodriver' folder, choose the folder for your system and unzip the program, without changing any path.
