### ISSUE TITLE
When try to start the bot don't get "way"

### ISSUE THREAD

**Issue by joost-heijden** [alpdias/instagram-bot#9]
Hi, when i try to start the bot, i can't import the Gecko path. Can you tell me what i need to do?

![instagrambot](https://user-images.githubusercontent.com/29427775/101757191-251d7800-3ad7-11eb-9d28-03145dc1baff.jpg)

**Comment by alpdias** [comment]
Hello, you need to enter the directory corresponding to your operating system and unzip the geckodriver, that's all, there is no need to move or anything, just unzip it on the spot

**Comment by joost-heijden** [comment]
I already unzipped the Geckodriver on the spot.

What i use is: 
`cd C:\Users\user name\Downloads\instagram-bot-master\src\`

After that i use:
`python botInstagram.py`

And then i get the screenshot above.

There is no way to drop the Configuration, and put the path for the Geckodriver

**Comment by alpdias** [comment]
Yes, there is a way, before it was like that, but as people got confused when it was time to put the path, I let him look for it myself, so I find it strange to be returning this error, try running the script 'botError.py' and show me what he returns you.

**Comment by joost-heijden** [comment]
When i try to activate "botError.py" it opens the Instabot start file.

![bot-error](https://user-images.githubusercontent.com/29427775/101791536-ef42b880-3b03-11eb-85f9-398b83119a54.jpg)

And without python, it opens Python. And it shows me the same:
![geckodriver](https://user-images.githubusercontent.com/29427775/101791994-7abc4980-3b04-11eb-8cbe-856e5c5d5ba4.jpg)

**Comment by alpdias** [comment]
Yes, the 'botError.py' file starts all other files, but without excess errors, which brings the real reason for the error that is happening. Now if you just want to put the geckodriver path directly in the code change this part as below the variables described as `way` and put the path to the geckodriver.

![image](https://user-images.githubusercontent.com/52184239/101810885-15625b80-3af8-11eb-8dd5-ce3ed3d60c5b.png)

**Comment by joost-heijden** [comment]
Get another error:

```
Traceback (most recent call last):
  File "botInstagram.py", line 14, in <module>
    import botStories
  File "C:\Users\username\Downloads\instagram-bot-master\src\botStories.py", line 33
    way = Path('C:\Users\username\Downloads\instagram-bot-master\geckodriver\windows\')
                                                                                              ^
SyntaxError: EOL while scanning string literal
```

The path that i put in the file is:
C:\Users\Username\Downloads\instagram-bot-master\geckodriver\windows\

If you wanna know if i extract the zipfile: yes i did

```
    # check the system
    if mySystem == 'Linux': 
        mySystem = 'clear'
        way = Path('C:geckodriver/linux/geckodriver-v0.26.0-linux64') # path to the file
        geckoFile = way / 'geckodriver' # way to geckodriver

    else:
        mySystem = 'cls'
        way = Path('C:\Users\username\Downloads\instagram-bot-master\geckodriver\windows\') 
        geckoFile = way / 'geckodriver.exe'
```

Even try to change the path for Windows (where i'm working on)

**Comment by alpdias** [comment]
Hello, sorry for the delay in the response, but try something like the image below, passing the direct path to the geckodriver and executable, just like in the image. I ended up also passing the wrong variable to the correct one would be `geckoFile`.

![image](https://user-images.githubusercontent.com/52184239/101990145-d103c680-3c83-11eb-821d-58dce34de356.png)

**Comment by joost-heijden** [comment]
I make a change, like you said. Now i get another error:

`SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape`

My code:
else:
```
        mySystem = 'cls'
        way = Path('C:\Users\username\Downloads\instagram-bot-master\geckodriver\windows\geckodriver-v0.26.0-win64\checkodrive.exe') 
        geckoFile = way / 'geckodriver.exe'
```

And to be sure: i need to change the path in all these files:
botDraw.py
botError.py
botLike.py
botStories.py

**Comment by alpdias** [comment]
Instead of putting the path in the `way` variable, put it in the `geckoFile` variable. The variable `way` uses the `Path` library so it is returning this error, so return it to the original and put your path directly in `geckoFile`.

**Comment by joost-heijden** [comment]
Again, same error:

```
Loading...

DRIVER ERROR! Check installed drive or path.
UNEXPECTED ERROR ON LOGIN, please try again and verify your connection!
UNEXPECTED ERROR ON HASHTAG PAGE, please try again and verify your connection!
UNEXPECTED ERROR ON COMMENT, please try again and verify your connection!
```

```
    else:
        mySystem = 'cls'
        way = Path('geckodriver/windows') 
        geckoFile = way / 'C:/Users/username/Downloads/instagram-bot-master/geckodriver/windows/geckodriver-v0.26.0-win64/'
```

**Comment by alpdias** [comment]
Follow this way, only the path in the variable

![image](https://user-images.githubusercontent.com/52184239/102101389-52389600-3e09-11eb-8740-1f73e7413a88.png)

**Comment by joost-heijden** [comment]
```
    else:
        mySystem = 'cls'
        way = Path('geckodriver/windows') 
        geckoFile = way / 'C:\Users\username\Downloads\instagram-bot-master\geckodriver\windows\geckodriver-v0.26.0=win64\geckodriver.exe'
```

Still this error:

```
DRIVER ERROR! Check installed drive or path.
UNEXPECTED ERROR ON LOGIN, please try again and verify your connection!
UNEXPECTED ERROR ON HASHTAG PAGE, please try again and verify your connection!
UNEXPECTED ERROR ON COMMENT, please try again and verify your connection!
```
